### PR TITLE
Smaller fixes and changes

### PR DESCRIPTION
**Pull request by mrueg**
Some smaller cleanups and updates.
* Update dependencies
* Test against more recent versions of golang
* Drop outdated fallback code

### CODE REVIEW

**Review by roidelapluie — COMMENTED** [review]
Thanks for your pull request. The golint workflow file is propagated from prometheus/prometheus and can not be changed in this repository. Additionally, the TLS tests should not cover all the cases, just enough to be working as expected, so  I don't think we should make them version dependent.

**Comment by mrueg** [comment]
Thanks for the quick feedback, I've dropped the golangci-lint change and hope the change will make it work on go1.16 as well. 

I changed the order of the output for bad cipher selection, please check if my assumption there was correct.

Unfortunately  for the `valid tls config yml with multiple client ciphers` it seems like there's a difference in preference since go 1.17:
`AES-128 is preferred over AES-256 for encryption.`  https://go.dev/blog/tls-cipher-suites (so it picks a different one than with go 1.16)

I can pick other ciphers, unless you have a different idea?

**Comment by roidelapluie** [comment]
Yes, let's pick other ciphers for testing.

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thank you!

**Pull request merged**
