### PR TITLE
Change format of listen on vsock

### PR DESCRIPTION
**Pull request by Leonid99**
Before this change, the expected format of listening on
vsock was "--web.listen-address=vsock://:9100".
However, this URI-inspired format is probably confusing,
especially given that it doesn't really support the host
portion of the URI and that listening on TCP doesn't
support the "http://:9100" syntax.
This commit changes the expected format for vsock to be
--web.listen-address=vsock:9100.

### CODE REVIEW

**Comment by Leonid99** [comment]
Found #202 after publishing this PR. Should I just close this one? (They are identical, except for the expected format of the command line flag).

**Comment by SuperQ** [comment]
I think the other PR is mostly ready to go. Would you be interested in adding to the tests as mentioned in the comments after I merge it?

**Comment by SuperQ** [comment]
If you have any comments on the other PR, feel free to contribute there.

**Comment by Leonid99** [comment]
> If you have any comments on the other PR, feel free to contribute there.

Left a few comments.

**Comment by Leonid99** [comment]
@SuperQ I rebased this branch on top of the one by @jeffrey4l to address my own remarks in his #202. Would you be interested in me rebasing this branch to resolve conflicts, so that we can merge it? I will obviously keep @jeffrey4l 's commits untouched to keep proper credit.

**Pull request closed without merging**
