### PR TITLE
Add missing sample configuration file

### LINKED ISSUE #65: A sample configuration file link is not working
In the file exporter-toolkit/docs/web-configuration.md
the link is not working. the response is 404
image

### PR DESCRIPTION
**Pull request by LeviHarrison**
This PR fixes a link to a non-existent sample configuration file in https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md by adding one. The file is mostly copied from https://github.com/prometheus/prometheus/blob/main/documentation/examples/web-config.yml with the following small changes:

```diff
8,9c8,9
< # Usernames and passwords required to connect.
< # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt.
---
> # Usernames and passwords required to connect to Prometheus.
> # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
```

Fixes #65

### CODE REVIEW

**Comment by SuperQ** [comment]
The link in the docs should be updated to point to https://github.com/prometheus/exporter-toolkit/blob/master/web/web-config.yml.

**Review by RichiH — APPROVED** [review]

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Comment by SuperQ** [comment]
Err, that's not what I meant. The example config is in the `web` dir.

**Comment by LeviHarrison** [comment]
Whoops... I see that now. This one exercises more of the fields, but we should probably only have one.

**Comment by SuperQ** [comment]
Yes, this is definitely a better example, we just need to pick one.

**Comment by LeviHarrison** [comment]
I prefer `docs` because that's where the configuration is documented.

**Pull request merged**
